baseURL = 'https://superMDguy.github.io/'
languageCode = 'en-us'
title = 'My Homepage'
author = 'Matthew Dangerfield'
copyright = 'Copyright © 2022 Matthew Dangerfield'
theme = 'paper'

[params]
  twitter = 'superMDguy'
  github = 'superMDguy'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

