baseURL = 'https://superMDguy.github.io/'
languageCode = 'en-us'
title = "Matthew's Homepage"
author = 'Matthew Dangerfield'
copyright = 'Copyright © 2025 Matthew Dangerfield'
theme = 'paper'

[params]
twitter = 'superMDguy'
github = 'superMDguy'
linkedin = 'matthew-dangerfield'
favicon = "/favicon.ico"

[menu]
[[menu.main]]
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 10

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
